### ISSUE TITLE
New Search Field

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/igb-geonode#10]
Include a new field in the search/filter function for groups (if possible including group categories).

The idea is enable two new search fields, groups and groups categories. They would work as usual which means GeoNode performs a logical AND between the selections of the various search field.

**Comment by simboss** [comment]
The idea is have this as a new feature on standard GeoNode rather than on a client's specific customization.

Please, start by writing a plan on this issue which might require us to write a GNIP.

**Comment by ricardogsilva** [comment]
I went ahead and submitted a PR with the implementation of this in the same way as the other already existing geonode filters:

geosolutions-it/geonode#323

PR is currently pending moderation. It allows filtering a layer's `group` and `group categories`.

IMO, since the proposed implementation follows already existing practices and just adds two new filters, it probably would not require a GNIP.

**Comment by ricardogsilva** [comment]
My PR has been reviewed and merged to main GeoNode, so I guess we may consider this done
