### ISSUE TITLE
Self registration

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/igb-geonode#8]
External users should be able to register at the site.

For this we are going to use built in functionalities of GeoNode. Users will be able to sign up directly on GeoNode also using social login with Linkedin and Facebook.
Notice that these users will be only local to GeoNode; GeoNode will not write to the LDAP server from IGB but will only pull users and groups

**Comment by ricardogsilva** [comment]
For integration of social logins, I've been looking at setting up LinkedIn login. It seems their API has changed a bit and in order to be able to use their OAuth2 services one needs to create an app **and** also state which company is responsible for it.

So I guess I'll either need access to a GeoSolutions LinkedIn app for testing [1], if something like this already exists, or we'll need to create one for this.

[1] - https://www.linkedin.com/developers/apps/new

**Comment by giohappy** [comment]
@ricardogsilva isn't django-allauth Linkedin provider aligned?

**Comment by ricardogsilva** [comment]
I think so, but what I meant is that LinkedIn's Terms of Service seem to have changed since last time I used the geonode integration - they now explicitly require that any new integration apps (like our social login) be endorsed by an existing organization profile. This means I cannot even get to the point where I am testing django-allauth with LinkedIn yet, as I've not been able to create an app on their developer website.

**Comment by giohappy** [comment]
Ok, I see your point. The same happens for other third party social logins too (even Github, AFAIK).
@simboss  for testing purposes I think we should use the GeoSolutions account to setup the app (as we do for GeoNode social logins, Google services, etc.).

**Comment by ricardogsilva** [comment]
I've also been checking out the Facebook integration, and sincle last I used it, Facebook has also introduced some changes. 

The one change I am currently stumbling on is that Facebook now [requires all apps to use HTTPS](https://developers.facebook.com/docs/facebook-login/security/#https) - I'm about to setup a local HTTPS cert using [mkcert](https://github.com/FiloSottile/mkcert) for being able to test this out locally

**Comment by giohappy** [comment]
nkcert is nice, I didn't know it.
How can it provide trusted HTTPS app to FB though?

**Comment by ricardogsilva** [comment]
`mkcert` can be used to setup a local Certificate Authority and also for generating cert/key pairs which are not self signed.

I've set it up locally and it is working nicely in conjunction with [django-sslserver](https://github.com/teddziuba/django-sslserver).

With this setup I am able to use `HTTPS` locally (for dev only) and I've since been able to get the Facbook Oauth2 integration to work OK.

**Comment by giohappy** [comment]
so FB Oauth2 accepts redirects to local URI?

**Comment by ricardogsilva** [comment]
> so FB Oauth2 accepts redirects to local URI?

yes! seems crazy, but it works :smile:

**Comment by ricardogsilva** [comment]
after configuring a linkedin provider, I'm still not being able to login due to the error:

```
An error occurred while attempting to login via your social network account.
Code:unknown, Error: 403 Client Error: Forbidden for url: https://api.linkedin.com/v2/me?projection=(emailAddress,firstName,headline,id,industry,lastName,pictureUrl,positions,publicProfileUrl,location,specialties,summary) 
```

Looking through alluth's issue list I found this

**Comment by simboss** [comment]
keep us posted.

If facebook works fine we can live with it for the time being and revisit later on.

**Comment by simboss** [comment]
@ricardogsilva make sure we stay within the original estimates, if you see a risk we go beyond talk to me.

**Comment by ricardogsilva** [comment]
So I eventually was able to get both facebook and linkedin logins to work.

-  facebook works if we have an HTTPS enabled env

-  linkedin needed some additional work in geonode to adjust to some recent changes in their API. I've a PR waiting for review that fixes it directly on geonode:

**Comment by simboss** [comment]
@ricardogsilva please, follow up with @afabiani and @giohappy to get this reviewed and eventually merged.
